name: Push to All Branches

on:
  push:
    branches:
      - main

jobs:
  push-to-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Push to all branches
        run: |
          git fetch --all
          for branch in $(git branch -r | grep -v '\->' | sed 's,origin/,,'); do
            if [ "$branch" != "main" ] && [ "$branch" != "HEAD" ]; then
              git checkout "$branch"
              git merge origin/main
              git push origin "$branch"
            fi
          done